server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # Create, update, validate, none
      show-sql: true # Show SQL in console
  build: # This section might need to be moved to another part of the configuration, depending on its purpose.
    version: "1.0"
